### ISSUE TITLE
Introduce rules to enable/disable features

### ISSUE THREAD

**Issue by totorewa** [disrespecTech/rugserver#1]
Add carpet-style rules to the mod to enable, disable, or configure the features it offers.

Rules to be modifiable with the command `/rug`. Rules should be contained within a single class as static fields, which is reflected upon on startup to build valid usable arguments for the `rug` command. A rule change is not persisted however the default value can be configured.

Proposed rules:

- `/rug antiCheatDisabled <true/false>` - Disables some anti-cheat checks
- `/rug commandCamera <true/false/op>` - Enables the use of camera mode via `/cs`
- `/rug commandPlayer <true/false/op>` - Enables the use of `/player`
- `/rug cameraModeDisableDamageCooldown <true/false/op>` - Disable the damage cooldown that prevents players entering camera mode after recently taking damage
- `/rug carefulBreak <true/false>` - Allows careful break to be enabled via `/log carefulBreak`
- `/rug setDefaults <rule> <value>` - Sets the default value for a rule
- `/rug sleepPercentage <0-100>` - Percentage of non-bot, non-afk**¹** players that must be sleeping to skip the night.

**¹** Marking players as AFK is not yet a feature

**Comment by DesktopFolder** [comment]
why yes this does seem like a good idea 🚀
